### ISSUE TITLE
Consider renaming?

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-computed-decorators#102]
We currently have decorators for a number of things other than `Ember.computed`. I think renaming to something more general may be a good idea.

Some suggestions:

* `ember-ornamentalist`
* `ember-decorators`
* `ember-decorator-grab-bag` 
* `ember-decorator-bonanza`

**Comment by rwjblue** [comment]
@stefanpenner / @wycats / @tomdale / @pzuraq / @mmun / everyone - Thoughts?

**Comment by pzuraq** [comment]
I think providing primitives is a good idea, especially as we start using decorators more and more. We probably need to refine the current helpers a bit, and build out more decorators that cover other Ember functionality to make sure that they are robust enough before we make them an official public API (may want to put them into a `-private` folder for the time being then too?)

I think `ember-decorators` works, but also sounds very Officially Ember™️. These are still kind of experimental, so maybe `ember-decorator-grab-bag` or `bonanza` makes more sense?

**Comment by tomdale** [comment]
@kellyselden Given that decorators are "just functions," what primitives are you thinking might be useful here? I wonder if there is sugar for decorators that is not necessarily Ember specific.

@pzuraq FWIW one of the motivations for using the `@ember` package scope in the module API is to make it clear which things are official or not, because anyone can (and should!) create packages with the `ember-` prefix. If we can signal whether something is "official" by calling it `@ember/decorators` for example, I think the short-and-sweet `ember-decorators` is fine.

**Comment by kellyselden** [comment]
@tomdale Not necessarily. Anyone that wants to make a decorator with the same array semantics would have to recreate the '.@each' and '.[]' handling, as well as other gotchas. Also if this addon implements the composing mentioned in #99, that's another layer someone would have to do their self.

**Comment by pzuraq** [comment]
Sweet, I think `ember-decorators` is perfect then 😄

Regarding primitives, I believe the `.@each` and `.[]` handling @kellyselden is referring too may have been dropped in favor of thin wrapping ember-macro-helpers? Either way, I agree they would probably be more general than Ember, we can probably extract them into another package at some point.

**Comment by rwjblue** [comment]
OK, seems good.  Lets rename to `ember-decorators`. 

Anyone have time to work on updating the repo?

**Comment by pzuraq** [comment]
I can do it! I was also hoping we could use the opportunity as a breaking change to reorganize the decorators to be a bit more inline with the future [javascript module API](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md). Mainly would like to export `@computed` as a named function, and move all the computed macros to a separate file.

**Comment by rwjblue** [comment]
@pzuraq - Sounds good!
