### ISSUE TITLE
How "bleeding edge" is this project?

### ISSUE THREAD

**Issue by toranb** [rwjblue/ember-computed-decorators#12]
Robert

I love the new syntax you show in this project but I'm curious how "bleeding edge" / "breaking" this is today. I'm asking as someone who is looking to pull this in / use it / not have a team of devs blow up on me when it stops working in 30 days :)

In all seriousness - I'll be following this personally regardless but I'm asking the question above to understand if I should pull it in at work (or wait a bit to see it mature).

Thanks for such a great project @rwjblue  !!!

**Comment by xtian** [comment]
I'm wondering the same thing. I'd love to start using the new syntax unless this is still highly experimental.

**Comment by mgenev** [comment]
Decorators are here to stay. They're a native es7 feature. Aurelia is already using them.

**Comment by stefanpenner** [comment]
It is pretty bleeding edge. Decorators are here to stay, but we may have slight adjustments in this project as we use it more. Only way we can learn what those are though are to get it into the wild.

**Comment by toranb** [comment]
Agreed and agreed :)

Just glad to see you guys pushing ahead - love this stuff myself :D
