### ISSUE TITLE
Computed decorators do not work with Babel 5.1.13

### ISSUE THREAD

**Issue by OrKoN** [rwjblue/ember-computed-decorators#14]
The calling code is the following:

```javascript
var MyComponent = Ember.Component.extend({
  layout: layout,
  tagName: 'h4',

  key: 'my-key',

  @computed('key')
  test(key) {
    return `${key} + computed`;
  }

});
```

With Ember 1.12.0-beta.1 I see this error: ember.debug.js:41940 Uncaught TypeError: unsupported content. Looks like Ember tries to render the `test` function as the content.

Worked before I updated Babel (was using 5.1.8) but I am not sure whether it's a problem of the code in this repo or of the Babel.

**Comment by mgenev** [comment]
same here, ember 1.12 beta and babel 5, this doesn't work

**Comment by mgenev** [comment]
Just tried again, the babel-core version being used by ember-cli-babel/broccoli-babel-transpiler is 5.2.16, but the computed still doesn't run

**Comment by stefanpenner** [comment]
i'll look.

**Comment by OrKoN** [comment]
Works now with:

```
npm:babel-core 5.4.2
npm:babel-runtime 5.4.2
```
