### ISSUE TITLE
Should observers receive their dependents as arguments, like computed already does?

### ISSUE THREAD

**Issue by martndemus** [rwjblue/ember-computed-decorators#36]
```js
@observes('foo')
bar(foo) { 
  // use foo
}
```

**Comment by stefanpenner** [comment]
No they shouldn't. Because observers are sync, when one uses them one likely should also use a ember.run.scheduleOnce. If we get automatically, we will force sync consumption

**Comment by martndemus** [comment]
Right, forgot about that.

**Comment by rosshadden** [comment]
@stefanpenner Can you elaborate on your answer a little?  I think you are saying that observed properties should be accessed after the run loop is over, in case the value changes again later in the run loop.  Is that the right idea?
