### ISSUE TITLE
Add test for @computed passing in nested property

### ISSUE THREAD

**Issue by SaladFork** [rwjblue/ember-computed-decorators#37]
Per discussion with @rwjblue and [another issue](https://github.com/rwjblue/ember-computed-decorators/issues/20#issuecomment-103964356), we should expect `@computed('foo.bar')` to pass the value of `foo.bar` to the callback function. There is currently no test for this (though [there are for `attr.models.@each` and `attr.models.[]`](https://github.com/rwjblue/ember-computed-decorators/blob/master/tests/unit/computed-test.js#L165-L213)).

**Comment by rwjblue** [comment]
:+1: to MOAR tests.  From a brief review of the code, I *think* that the test should pass right off the bat (i.e. no changes should be needed).

**Comment by SaladFork** [comment]
Great! I'll make a PR :)
