### ISSUE TITLE
Discussion about property brace expansion

### ISSUE THREAD

**Issue by SaladFork** [rwjblue/ember-computed-decorators#38]
The [current behavior](https://github.com/rwjblue/ember-computed-decorators/blob/287e26eba58f18425572d1d6dc9bf126a7d679f5/tests/unit/computed-test.js#L215-L239) is that `@computed('attr.{foo,bar}')` will pass the value of `attr` to the callback function.

Property brace expansion is often [shown as an interchangeable shortcut for multiple keys](http://emberjs.com/blog/2014/02/12/ember-1-4-0-and-ember-1-5-0-beta-released.html#toc_property-brace-expansion), so I would expect `@computed('attr.{foo,bar}')` to behave like `@computed('attr.foo', 'attr.bar')`. However, [the latter will pass](https://github.com/rwjblue/ember-computed-decorators/issues/37) the values of `attr.foo` and `attr.bar` to the callback function.

decorator | expected args | actual args
------------- | ------------ | --------
`@computed('attr.foo', 'attr.bar')` | `attr.foo`, `attr.bar` | `attr.foo`, `attr.bar`
`@computed('attr.{foo,bar}')` | `attr.foo`, `attr.bar` | `attr`

cc @martndemus

**Comment by rwjblue** [comment]
I would be perfectly fine with this, but I do not want to duplicate the logic of [expand_properties](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/expand_properties.js) in this repo.  If we can do this via `Ember.expandProperties`, I am :+1:.

**Comment by jcbvm** [comment]
@rwjblue This issue seems to be solved in version 0.2.0, can this issue be closed?
