### ISSUE TITLE
Add decorators for observes and on 

### ISSUE THREAD

**Issue by OrKoN** [rwjblue/ember-computed-decorators#4]
for `observes`:

```javascript
  @observes('model')
  onUpdate(model) {
    ...
  },
```

for `on`:
```javascript
  @on('init')
  setup() {
    ... do stuff ..
  }
```

**Comment by knownasilya** [comment]
Would probably require renaming the addon.

**Comment by stefanpenner** [comment]
done: https://github.com/rwjblue/ember-computed-decorators/blob/master/addon/index.js#L30-L31

**Comment by knownasilya** [comment]
Sweetness!

**Comment by OrKoN** [comment]
Looks very good! Thank you. I have a question about the interface of @observes. It looks like it's different from the one of @computed:

```JavaScript
  @observes('key', 'key2')
  onUpdate(targetObj, keyName) { // instead of onUpdate(newKeyValue, newKey2value)
    console.log('@observes');
    console.log(arguments)
    console.log('Observer fires - key was updated', targetObj.get(keyName));
  },
```

whereas @computed handler gets the actual values of observed attributes. Is it different on purpose?

Also is it possible to handle the following case? Does not work for me at the moment:

```JavaScript
  @observes('key')
  @on('init')
  onUpdate(targetObj, keyName) {
    console.log('@observes');
    console.log(arguments)
    console.log('Observer fires - key was updated', targetObj.get(keyName));
  }
```

**Comment by stefanpenner** [comment]
> Also is it possible to handle the following case? Does not work for me at the moment:

see: https://github.com/rwjblue/ember-computed-decorators/issues/18

**Comment by stefanpenner** [comment]
> whereas @computed handler gets the actual values of observed attributes. Is it different on purpose?

hmm, likely a bug. That begin said, `observers` really are an anti-pattern 90% of the time. Avoid using them ;)

**Comment by knownasilya** [comment]
@stefanpenner when are they not an anti-pattern, and what's the alternative?

**Comment by stefanpenner** [comment]
> @stefanpenner when are they not an anti-pattern, and what's the alternative?

basically, they are dubious unless pushing data out of ember. And they must do so very carefully.

**Comment by rwjblue** [comment]
I believe this is done.
