### ISSUE TITLE
It no work on 2.0 

### ISSUE THREAD

**Issue by mobinni** [rwjblue/ember-computed-decorators#41]
I can't seem to import the required module on ember 2.0
WHY GOD

**Comment by rwjblue** [comment]
This isn't terribly actionable, can you please share details and/or a reproduction so that we can help you?

**Comment by mobinni** [comment]
I'm sorry to be more clear:
When generating a project with Ember CLI in conjunction with Ember version 2.0 the decorator package breaks. Ember won't allow an import of this module via NPM. 

Following pull request may solve it:  https://github.com/rwjblue/ember-computed-decorators/pull/40

However the error that occurs is:
Uncaught Error: Could not find module `ember-computed-decorators` imported from `...`

**Comment by rwjblue** [comment]
When you open the app in Chrome (after `ember serve`) do you have any other errors?

Generally, this error happens because `vendor.js` threw an error during evaluation (most common cause currently is using Ember Data 1.x with Ember 2.x)...

**Comment by mobinni** [comment]
I looked into this however the problem persisted

**Comment by rwjblue** [comment]
Please provide a reproduction demonstrating the issue.  I do not think this is directly an issue with this addon, but I can't really help with out more details.

**Comment by mobinni** [comment]
So I went over the issue and started from zero and reimplemented your suggestions and it indeed was because ember-data was not 2.0. Thanks for your fix!
