### ISSUE TITLE
It would be nice to have a new version published.

### ISSUE THREAD

**Issue by martndemus** [rwjblue/ember-computed-decorators#43]
Pretty please :smile:

**Comment by rwjblue** [comment]
We need to figure out what is going on in https://github.com/rwjblue/ember-computed-decorators/pull/40

**Comment by martndemus** [comment]
On it!

**Comment by jevanlingen** [comment]
I see in the bower config file `ember": "2.1.0"` and #40 is closed, so this ticket can be closed right?

**Comment by rwjblue** [comment]
Yep, thanks for pointing that out!
