### ISSUE TITLE
import everywhere / inject

### ISSUE THREAD

**Issue by Leooo** [rwjblue/ember-computed-decorators#51]
Hello, newbie ES6 question here:

Is there a way to import the decorators in, say, all controllers?

=> I don't see myself adding `````import computed, {uniq,union,sum,sort,setDiff,reads,readOnly,or,
  and,oneWay,notEmpty,not,none,min,max,match,mapBy,map,lte,lt,intersect,gte,gt,filterBy,filter,equal,empty,
  collect, bool,alias} from 'ember-computed-decorators';````` in all my controllers.

Though I could probably import at least `computed`, which seems the most essential for not DRY.

I tried to `import * as deco from 'ember-computed-decorators'` but it doesnt seem to work with the @ convention

Thanks

**Comment by rwjblue** [comment]
No, the point is that you import what you need in each file. 

I suppose you could figure out a way to make them global, but I do not think that is a good idea.

**Comment by rwjblue** [comment]
You should be able to use the "* as" syntax though.

**Comment by Leooo** [comment]
Didn't manage to make the * syntax work for now.

For importing what you need, it seems to me that in most cases it takes as long to write "Ember.computed .lte" than adding it in the imports. Though for importing `computed` it will still be very very useful so i will use this one.
