### ISSUE TITLE
Trying to fix linting errors

### ISSUE THREAD

**Issue by brancusi** [rwjblue/ember-computed-decorators#59]
Really like using this addon. Have been trying to fix the linting errors though and been struggling.

Switching to eslint has removed the `@decorator` warning, but when using `@alias` I am still getting lint errors.

```
@alias('model.code')code
```

Results in
```
 9:3  error  "code" is not defined      no-undef
```

Came across this issue: [https://github.com/babel/babel-eslint/issues/204](https://github.com/babel/babel-eslint/issues/204)

Any ideas?

I basically have this is so many places, the thought of adding ignore flags almost seems to defeat the purpose of the addon for me.

Thanks

**Comment by topaxi** [comment]
The problem is, this way you are referencing the variable code from the outer scope. Your example roughly translates to

```js
@alias('model.code') code: code
```

I usually define these as

```js
@alias('model.code') code: null
```

**Comment by brancusi** [comment]
Thanks @topaxi, I see now.

I am going to switch to Ember.computed.alias in these cases.
