### ISSUE TITLE
Unexpected '@' messages from jshint

### ISSUE THREAD

**Issue by ianpetzer** [rwjblue/ember-computed-decorators#69]
Hi there,

I've read some other issues on this repo about JSHint not support annotations as they are still a stage 1 proposal.

I was just wondering what we should do in order to use the annotations and not get failures in our build. Is the best solution to migrate to Eslint instead of JSHint?

Thanks for any advice!

**Comment by ianpetzer** [comment]
I've got advice on ember slack community to change to ESLint.

**Comment by rwjblue** [comment]
Yes, replace ember-cli-jshint with ember-cli-eslint. You can use polyjuice to help migrate you custom JSHInt config.

**Comment by ianpetzer** [comment]
Thanks so much for the advice!

**Comment by linearza** [comment]
@rwjblue Hi! We have mostly succesfully converted to eslint, I just have one question, im struggling to get anything in the format of `@reads('someProp') undefineProp,`, be that `@mapBy`, or `@alias` etc. to pass as define variables, where eslint errors out on `no-undef` - do you perhaps know of a solution?

**Comment by ianpetzer** [comment]
This might help https://github.com/rwjblue/ember-computed-decorators/issues/59#issuecomment-174417204
