### ISSUE TITLE
Equal evaluating to false, when equal

### ISSUE THREAD

**Issue by linearza** [rwjblue/ember-computed-decorators#75]
Hi there

I have a scenario to the following effect:

```@equal('incrementedProp', 'compProp') isEqual: false,```

```@computed('otherProp')
compProp(otherProp) {
  return otherProp;
},
```

In the above scenario `isEqual` never evaluates to true, even when the properties are in fact equal as logged - when logging the two dependant properties and isEqual (compProp, incrementedProp, isEqual) I get the following for example: `1 1 false` 

Additionally changing it to a computed property works as expected:

```
@computed('incrementedProp', 'compProp')
isEqual(incrementedProp, compProp) {
  return incrementedProp === compProp;
},
```

**Comment by ctjhoa** [comment]
@linearza a bit late but `@equal` works like [Ember.computed.equal](http://emberjs.com/api/classes/Ember.computed.html#method_equal). It means you actually compare `1` to the string `compProp`.

**Comment by linearza** [comment]
I see! thanks, closing
