### ISSUE TITLE
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed

### ISSUE THREAD

**Issue by GCorbel** [rwjblue/ember-computed-decorators#90]
Hi,

I'm trying to update to ember 2.13 and it seems there is a problem with babel 6. I have this error : 

```
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
SyntaxError: tiny/components/kh-health-card-field.js: Unexpected token (10:2)
   8 |   classNameBindings: ['customField.property'],
   9 |
> 10 |   @computed('customField.property')
     |   ^
  11 |   details() {
  12 |     const property = this.get('customField.property');
  13 |     const type = this.get('customField.type');
    at Parser.pp$5.raise (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1705:8)
    at Parser.pp$1.parseDecorator (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1885:10)
    at Parser.pp$3.parseObj (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3887:28)
    at Parser.pp$3.parseExprAtom (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3639:19)
    at Parser.pp$3.parseExprSubscripts (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3414:19)
    at Parser.pp$3.parseMaybeUnary (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$3.parseExprListItem (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:4190:16)
    at Parser.pp$3.parseCallExpressionArguments (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3493:20)
    at Parser.pp$3.parseSubscripts (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3453:31)
    at Parser.pp$3.parseExprSubscripts (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3424:15)
    at Parser.pp$3.parseMaybeUnary (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:3264:19)
    at Parser.pp$1.parseExport (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:2571:19)
    at Parser.pp$1.parseStatement (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1830:74)
    at Parser.pp$1.parseBlockBody (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:2212:21)
    at Parser.pp$1.parseTopLevel (/home/dougui/workspace/tiny/frontend/node_modules/babylon/lib/index.js:1723:8)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/home/dougui/workspace/tiny/frontend/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/home/dougui/workspace/tiny/frontend/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Class.transpileTree (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/index.js:38:48)
    at Object.toTree (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-babel/index.js:45:30)
    at /home/dougui/workspace/tiny/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessJs (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
    at EmberApp.appAndDependencies (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1110:27)
    at EmberApp.javascript (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1227:30)
    at EmberApp.toArray (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1664:12)
    at EmberApp.toTree (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1686:38)
    at module.exports (/home/dougui/workspace/tiny/frontend/ember-cli-build.js:25:14)
    at Builder.setupBroccoliBuilder (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/lib/models/command.js:242:46)
    at tryCatch (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/dougui/workspace/tiny/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at /home/dougui/workspace/tiny/frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:628:16
```
Here is my `ember-cli-build.js : 

```
/* eslint-env node */
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    babel: {
      optional: ['es7.decorators']
    }
  });

  return app.toTree();
};
```

The optional value doesn't make a difference.

**Comment by GCorbel** [comment]
I close this issue because this is not related to `ember-computed-decorators`.

**Comment by rwjblue** [comment]
We need to update the documentation here to show folks how to use it with ember-cli-babel@6:

```js

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    babel: {
      plugins: ['transform-decorators-legacy']
    }
  });

  return app.toTree();
};
```

Would you happen to have time for that?

**Comment by kellyselden** [comment]
I changed my code to the new style, and the error changed to:

```
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "base" at 0, attempted to resolve relative to "package-hint-historic-resolver/adapters"
    at C:\code\package-hint-historic-resolver\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
```

**Comment by rwjblue** [comment]
@kellyselden - Did you install the plugin?  In babel 6 all of the plugins are separate packages, so you would have to `yarn add --dev babel-plugin-transform-decorators-legacy` (or npm equivalent) first.

**Comment by kellyselden** [comment]
After doing that, new message is:

```
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
TypeError: The plugin "transform-decorators-legacy" didn't export a Plugin instance
    at PluginManager.validate (C:\Users\kelly\AppData\Roaming\npm\node_modules\ember-cli\node_modules\babel-core\lib\transformation\file\plugin-manager.js:164:13)
```

**Comment by rwjblue** [comment]
Can you do `npm ls babel-core`?  Are you using ember-cli@2.13 or an older version?

**Comment by rwjblue** [comment]
If you are using ember-cli < 2.13, you have to use:

```js
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    babel6: {
      plugins: ['transform-decorators-legacy']
    }
  });

  return app.toTree();
};
```

But for ember-cli@2.13+ you can just do:

```js
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    babel: {
      plugins: ['transform-decorators-legacy']
    }
  });

  return app.toTree();
};
```

**Comment by kellyselden** [comment]
That did it. I had yet to merge in ember-cli@2.13. The strange thing is it was working on Travis without any changes. Only local dev was failing. I don't think it's Windows related because the poster is Unix.

**Comment by GCorbel** [comment]
I changed for `transform-decorators-legacy` and installed `babel-plugin-transform-decorators-legacy` but there is no change.

**Comment by GCorbel** [comment]
Do you have any update? I still have the error.

**Comment by thec0keman** [comment]
Is someone else working on updating the documentation?  Otherwise I can take a stab at it tomorrow.

**Comment by GCorbel** [comment]
@thec0keman did you found the solution ?

**Comment by thec0keman** [comment]
We aren't 100% of the way there yet.  All of our addons are on babel 6 with little effort.

For the main app, things are a bit more complicated by in-repo addons and engines.  So far this has meant:
- making sure each in-repo addon has `"ember-computed-decorators": "*"` in its `package.json`
- making sure each in-repo addon correctly updates this code in `index.js`:
```
  init: function(app) {
    this._super.init && this._super.init.apply(this, arguments);

    this.options = this.options || {};
    this.options.babel = this.options.babel || {};
    this.options.babel.plugins = this.options.babel.plugins || [];

    if (this.options.babel.plugins.indexOf('transform-decorators-legacy') === -1) {
      this.options.babel.plugins.push('transform-decorators-legacy');
    }
  }
```

I think the second one was the biggest troll.  It looks like if you try to add the pre-babel 6 setup code from any addon, ember-cli gets very confused.

**Comment by rwjblue** [comment]
@thec0keman - FWIW, I wouldn't do that manually more than once or twice 😝.

I'd probably make a `lib/setup-decorators.js` that has:

```js
module.exports = function(addon) {
    addon.options = addon.options || {};
    addon.options.babel = addon.options.babel || {};
    addon.options.babel.plugins = addon.options.babel.plugins || [];

    if (addon.options.babel.plugins.indexOf('transform-decorators-legacy') === -1) {
      addon.options.babel.plugins.push('transform-decorators-legacy');
    }
};
```

Then in each of your in-repo-engines I'd do:

```js
var setupDecorators = require('../setup-decorators');

module.exports = {
  init() {
    this._super.init && this._super.init.apply(this, arguments);
    setupDecorators(this);
  }
};
```

Or something like that...

**Comment by GCorbel** [comment]
I don't understand why because I followed the steps you gave but I have this error message : 

```
File: ember-mocha.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
TypeError: The plugin "transform-decorators-legacy" didn't export a Plugin instance
```

I removed all my in repod addons just to be sure. I have this babel files in my package.json : 

```
cat package.json | grep babel
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babelify": "^7.2.0",
    "ember-cli-babel": "^6.0.0",
```

My ember-cli-build is a copy/paste of the @rwjblue one.

What's the error ?

**Comment by benbabics** [comment]
This thread makes me feel dumb. Do I need to execute this script above @rwjblue is talking about? 

As stated above by @GCorbel I too am getting `Unexpected token` because of a decorator (I did not have this issue for a separate app running `ember-cli@2.6.3, ember-cli-babel@^5.1.6.

I have a brand new ember app using `ember-cli@2.13.1`. 
In `ember-cli-build.js` I have the following:
```
var app = new EmberApp(defaults, {
  babel: {
    optional: ['transform-decorators-legacy']
  }
});
```

I have installed the babel plugin: `yarn add --dev babel-plugin-transform-decorators-legacy`, and when I run `npm ls babel-core`, I get the following:
```
npm ls babel-core
lickityclick@0.0.0 /Users/benbabics/Sites/lickityclick.com/client
├─┬ ember-bootstrap@0.8.0
│ ├─┬ ember-cli-babel@5.2.4
│ │ └─┬ broccoli-babel-transpiler@5.6.2
│ │   └── babel-core@5.8.38
│ └─┬ ember-wormhole@0.3.6
│   └─┬ ember-cli-babel@5.2.4
│     └─┬ broccoli-babel-transpiler@5.6.2
│       └── babel-core@5.8.38
├─┬ ember-cli@2.13.1
│ └─┬ broccoli-babel-transpiler@6.0.0-alpha.3
│   └── babel-core@6.24.1
├─┬ ember-cli-moment-shim@3.1.0
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.6.2
│     └── babel-core@5.8.38
├─┬ ember-computed-decorators@0.3.0
│ ├─┬ ember-cli-babel@5.2.4
│ │ └─┬ broccoli-babel-transpiler@5.6.2
│ │   └── babel-core@5.8.38
│ └─┬ ember-macro-helpers@0.6.1
│   └─┬ ember-cli-babel@5.2.4
│     └─┬ broccoli-babel-transpiler@5.6.2
│       └── babel-core@5.8.38
├─┬ ember-cookies@0.0.9
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.6.2
│     └── babel-core@5.8.38
├─┬ ember-lodash@4.17.2
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.6.2
│     └── babel-core@5.8.38
├─┬ ember-moment@7.3.0
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.6.2
│     └── babel-core@5.8.38
├─┬ ember-run-decorators@0.0.1
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.6.2
│     └── babel-core@5.8.38
├─┬ ember-simple-auth@1.3.0
│ ├─┬ ember-cookies@0.0.13
│ │ └─┬ ember-cli-babel@5.2.4
│ │   └─┬ broccoli-babel-transpiler@5.6.2
│ │     └── babel-core@5.8.38
│ └─┬ ember-getowner-polyfill@1.2.3
│   ├─┬ ember-cli-babel@5.2.4
│   │ └─┬ broccoli-babel-transpiler@5.6.2
│   │   └── babel-core@5.8.38
│   └─┬ ember-factory-for-polyfill@1.1.2
│     └─┬ ember-cli-babel@5.2.4
│       └─┬ broccoli-babel-transpiler@5.6.2
│         └── babel-core@5.8.38
├─┬ ember-toastr@1.4.1
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.6.2
│     └── babel-core@5.8.38
├─┬ ember-truth-helpers@1.3.0
│ └─┬ ember-cli-babel@5.2.4
│   └─┬ broccoli-babel-transpiler@5.6.2
│     └── babel-core@5.8.38
├─┬ ember-validated-form-buffer@0.1.0
│ ├─┬ ember-buffered-proxy@0.6.0
│ │ └─┬ ember-cli-babel@5.2.4
│ │   └─┬ broccoli-babel-transpiler@5.6.2
│ │     └── babel-core@5.8.38
│ ├─┬ ember-cli-babel@5.2.4
│ │ └─┬ broccoli-babel-transpiler@5.6.2
│ │   └── babel-core@5.8.38
│ └─┬ ember-cp-validations@3.3.2
│   ├─┬ ember-cli-babel@5.2.4
│   │ └─┬ broccoli-babel-transpiler@5.6.2
│   │   └── babel-core@5.8.38
│   ├─┬ ember-require-module@0.1.1
│   │ └─┬ ember-cli-babel@5.2.4
│   │   └─┬ broccoli-babel-transpiler@5.6.2
│   │     └── babel-core@5.8.38
│   ├─┬ ember-string-ishtmlsafe-polyfill@1.1.0
│   │ └─┬ ember-cli-babel@5.2.4
│   │   └─┬ broccoli-babel-transpiler@5.6.2
│   │     └── babel-core@5.8.38
│   └─┬ ember-validators@1.0.1
│     └─┬ ember-cli-babel@5.2.4
│       └─┬ broccoli-babel-transpiler@5.6.2
│         └── babel-core@5.8.38
└─┬ liquid-fire@0.27.3
  └─┬ ember-hash-helper-polyfill@0.1.2
    └─┬ ember-cli-babel@5.2.4
      └─┬ broccoli-babel-transpiler@5.6.2
        └── babel-core@5.8.38
```

Any insights on how to get this running would be greatly appreciated. :)

**Comment by rwjblue** [comment]
@benbabics double check my comment in https://github.com/rwjblue/ember-computed-decorators/issues/90#issuecomment-298241282. Unless you transposed when typing in here, you should be using `options.babel.plugins` but your snippet looked like you had `options.babel.optional`

**Comment by GCorbel** [comment]
Hi,

I reproduced the bug here : https://github.com/GCorbel/decorator_bug 

This is related to addons. It works with a brand new project but it fails when I add all addons I have for my project. I continue to clarify the situation.

**Comment by GCorbel** [comment]
It seems than ember-cli-mocha "0.13.2" create an error. Upgrade solve the problem but I have the same with a few other addons.

**Comment by benbabics** [comment]
Doh! That's exactly what I did wrong, @rwjblue. With that the build is successful again, however it does complain:

```
$ ember s
Livereload server on http://localhost:49153

/somepath/app/pods/components/signup-form/component.js
  31:3  error  Parsing error: Unexpected character '@'
✖ 1 problem (1 error, 0 warnings)

Build successful (7679ms) – Serving on http://localhost:4200/
```

Any thoughts?

**Comment by GCorbel** [comment]
@benbabics this is normal, it's just an eslint warning. Try to do `yarn add babel-eslint` and add `parser: 'babel-eslint'` in your .eslintrc.js

**Comment by benbabics** [comment]
👍🏻

**Comment by GCorbel** [comment]
@benbabics can you try to add ember-cli-mocha 0.13.2 just to confirm you have the same behavior than me? Thanks.

**Comment by GCorbel** [comment]
With a little more investigation, I saw [this commit](https://github.com/ember-cli/ember-cli-mocha/commit/9f9106ebc115099732444342978867e32d978566) solved the issue. @rwjblue you did it. (Thanks for your amazing contribution to the Ember community). 

I found the solution for other packages. Many of them depends of ember-cli-babel "^5.0" so it takes parameters we send in our ember-cli-build file and pass it in the old version. It fails because options are not compatible.

I tried to force to use the version 6 of ember-cli-babel by changing the `yarn.lock` file. It works but there is some problems with addons that use some es6 synthaxes.

I think we have to solutions : force all addons to update and don't be backward compatible or find a way to accept babel 5 options.

@kellyselden and @rwjblue what you think ?

**Comment by rwjblue** [comment]
@GCorbel - I don't fully understand what you mean.  Each "layer" (app and addon) can determine how it is transpiled. Prior to releasing ember-cli-babel@6 as the default in ember-cli@2.13 we tested apps and addons with various combinations of ember-cli-babel@5 and ember-cli-babel@6 and confirmed that each "layer" can function just fine using their own specific versions (as long as all plugins needed/added by the "layer" are also using the same).

**Comment by GCorbel** [comment]
I understand but option from `ember-cli-build` aren't passed in "layers". It fails with options I gave in this file with addons that depends of `ember-cli-babel 5`. I think it will search `transform-decorators-legacy` but it doesn't seems to find it. By forcing all addons to use babel 6, it works.

I may be wrong I'm not sure to understand all too.

**Comment by rwjblue** [comment]
As I mentioned above, in general, addons have always controlled their own transpilation. If a given addon is reading the host apps configuration and "doing something" with it to affect its own transpilation, then it will need to be updated to deal with babel@5 vs babel@6.  Most addons do not do this, and therefore are not affected.

I think this will be much more productive if we could talk concretely about specific combos of addons, so I can make sure that I understand what is going on for you and how we can address.  Can you provide a demo app that reproduces the issues you are facing?

**Comment by GCorbel** [comment]
You're right. I will give you an example very soon.

**Comment by GCorbel** [comment]
I did [this repo](https://github.com/GCorbel/decorator_bug2) when you can reproduce the bug. You can just to `yarn && ember build` to have the bug. It do this for a lot of addons.

**Comment by GCorbel** [comment]
I did [this branch](https://github.com/GCorbel/decorator_bug2/tree/working_version) with a working version where I force version of ember-cli-babel as you can see in [this commit](https://github.com/GCorbel/decorator_bug2/commit/6b89069f593a47bda0cd0abeea199d0d2c37acbd).

I have no idea what it do that. @rwjblue let me know if I can help more.

**Comment by GCorbel** [comment]
I finally found the reason and it was stupid thing. This is because I added a `.babelrc` file before I found the the with ember-mocha and I forgot it after. I removed this file and it works again.

Sorry for the time wasted and thank you.
