### ISSUE TITLE
Compatibility issues with babel6 and decorated properties

### ISSUE THREAD

**Issue by GCorbel** [rwjblue/ember-computed-decorators#94]
After fix build issues in #90 I continued to migrate my project and I have compatibility issues.

I have this kind of decorators : 

    @alias('session.endDate') sessionEndDate,

It worked with babel 5 but with the version 6 I have to use [transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy). It gives `sessionEndDate is undefined` as described in [this SO thread](http://stackoverflow.com/questions/43998822/attributes-are-not-defined-with-babel-6). To use properties this way I have to use [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) and I have to migrate all my project to use es6 classes which is a huge work.

I didn't found a way to use this kind of properties with "normal" objects. Let me know if I'm wrong but I search a lot and I didn't found a solution.

Any way, if there is a simple solution, the doc have to be updated. I can do it once I have the solution.

Thanks !

**Comment by rwjblue** [comment]
This seems like a duplicate of https://github.com/rwjblue/ember-computed-decorators/issues/93. Can you confirm?

**Comment by rwjblue** [comment]
The simplest solution is to use `@alias('session.endDate') sessionEndDate: null,`.

**Comment by GCorbel** [comment]
Yes your right. I searched for hours and you resolved this in 9 minutes, awesome. I didn't think to this simple solution. Thanks.
